### ISSUE TITLE
Making the theme "Hugo" Friendly

### ISSUE THREAD

**Issue by dudil** [SteveLane/hugo-icon#12]
Hi @SteveLane ,

Thank you for this project - It is very good skin in terms of design and simplicity.
However, the current way to setup the themes is strictly through config.toml which is not very Hugo friendly (adding text / items is really hard work).

I already modified that largely on my own project, but this will break the current implementation.
Let me know if you wish me to create a pull request or just preferred me to keep my own branch.

Cheers,
Dudi

**Comment by SteveLane** [comment]
Hi Dudi,

I'd love to take a look at what you've done, so a pull request would be great.

**Comment by carneybill** [comment]
@Dudil Did you fix the blogging capability on your project?

**Comment by dudil** [comment]
Sorry - I've moved into another theme but might be still to help.
@carneybill - can you elaborate what blogging capability are you looking for?

**Comment by carneybill** [comment]
@dudil On the Hugo site (https://themes.gohugo.io/hugo-icon/), it mentioned: "add blogging capability"  under To Do.  I'm new but can't figure out how to create a blogging tab/new post.  I was unsure if @SteveLane or you might have addressed it?

**Comment by SteveLane** [comment]
@carneybill I haven't addressed it yet, but it would be useful, so I opened it as a to do. Here's what I think would need to be done:

- [ ] add another partial for latest blog posts
- [ ] apply appropriate css classes - I think using something like the classes in the `mission` partial would work
- [ ] paginate the blog posts within that single page section
- [ ] create new single blog post template
- [ ] link each item to that single post

So, there's a bit of infrastructure needed before blogging can be added. (I didn't set the theme up with the intention of blogging straight away).

**Comment by dudil** [comment]
@SteveLane - Even though I’ve moved to another theme, I’ll be happy to assist. 
I have solid understanding of Hugo and can help with building it up. Will need more help with CSS etc. 
Also would love to add support for localization. 

Is that fine?

**Comment by SteveLane** [comment]
@dudil for sure! If you want to help out, that'd be great. This is not a high priority for myself.
