### ISSUE TITLE
Alt functionality for images

### ISSUE THREAD

**Issue by WaygoneWilco** [SteveLane/hugo-icon#14]
So far I haven't found a way to add alt text descriptions to images. Is this possible?

**Comment by SteveLane** [comment]
I'm not sure - the theme uses magnific for popups - I wonder whether adding alt to the <a> tag would work?

**Comment by WaygoneWilco** [comment]
Ok I will investigate - thank you

**Comment by WaygoneWilco** [comment]
I tried manually adding alt text to the images after running "hugo", but this did not work.

**Comment by SteveLane** [comment]
So, in team.html in the partials, you could add some go code to pick up an alt tag from the config, however I'm not too sure how to add it to the magnific popup.

**Comment by WaygoneWilco** [comment]
Ok, thank you. It seems like how the magnific popup is configure makes it so there can't be any alt tags. That's ok. Thanks for the help! I'll close this for now.
