### ISSUE TITLE
codes not interpreted in [[params.mission.item]]

### ISSUE THREAD

**Issue by avpavp** [SteveLane/hugo-icon#15]
I have 
[[params.mission.item]]
subtitle = "this and that with a super<sup>script</sup>"

but the <sup> tag is displayed just as <sup> - it doesn't get turned into a superscript.  Is this something that can be fixed in the theme?

Thanks

**Comment by avpavp** [comment]
Ah.  in mission.html (also services.html) there are some places where things aren't piped to "markdownify".  I just added " | markdownify" after .subtitle and my problem has been solved.

I would think this should be done throughout the theme - any reason not to?

**Comment by SteveLane** [comment]
Thanks!

No reason that I can recall, I probably just missed a few places...

Feel free to make changes and open a pull request ;)

**Comment by SteveLane** [comment]
fixed by #16 

Thanks!
