### ISSUE TITLE
in team section, adding 4th and 5th persons , they are not correctly align into 2 rows. 

### ISSUE THREAD

**Issue by gianghn** [SteveLane/hugo-icon#18]

**Comment by SteveLane** [comment]
Not sure what you mean. When I add the 4th and 5th, I get two rows of cards. Can you show a screenshot?

**Comment by zkamvar** [comment]
I ran into this problem as well. Here's a screencap:

![image](https://user-images.githubusercontent.com/3639446/46135012-22a70e80-c23c-11e8-82db-585e57a10121.png)

**Comment by SteveLane** [comment]
Interesting. I'd guess this is an issue with the base html5 theme.

As a test, if you 'pad' the descriptions for each contact so that they are the same length, what happens?

**Comment by zkamvar** [comment]
The thing is, it's really difficult to pad these boxes with the given content. However, if I have an identical component, then it aligns as expected: 
![image](https://user-images.githubusercontent.com/3639446/47024936-901ece80-d15a-11e8-9036-0789ba2c6070.png)

**Comment by SteveLane** [comment]
Hi @zkamvar I've made a fix in the `fix-for-flex` branch. Can you please pull down that branch and try it out?

**Comment by SteveLane** [comment]
Hi @zkamvar and @gianghn have you checked this? I'd like to close this issue.

**Comment by zkamvar** [comment]
Hi @SteveLane, thanks for your patience. When I use the code from 3519332, the cards are aligned but the color is gone and the menu header is narrower and left-justified:

![image](https://user-images.githubusercontent.com/3639446/49157615-20cef980-f318-11e8-9208-c6045ce365a9.png)

For reference, here's what the site looked like with the old version of hugo-icon:

![image](https://user-images.githubusercontent.com/3639446/49157683-4d831100-f318-11e8-9862-d9c576dc754a.png)

**Comment by SteveLane** [comment]
@zkamvar the first image is what it should look like given the default styling. All I could suggest is that maybe you adjusted some of the CSS in styles.css for your particular site, which get overwritten when you pull in those changes. In my testing, changing background colours etc works with no other side effects.

**Comment by TzZek** [comment]
@SteveLane , I've applied your changes in the branch fix-for-flex and it's working good for me now, thanks for that!

**Comment by SteveLane** [comment]
Thanks @TzZek I'll merge it in.
