### ISSUE TITLE
Netlify deploy a blank page

### ISSUE THREAD

**Issue by nodoambiental** [SteveLane/hugo-icon#25]
I built a hugo-icon web page on RStudio using blogdown (@yihui).
The deploy in the local host was perfect and very nice.
However, when I go to Netlify for deploy, the outcome is a blank page.
I checked for url basename and it corresponds to my domain.

Here the deploy details from Netlify:
12:24:48 AM: Build ready to start
12:24:51 AM: build-image version: 84aca9ba39e0ee86ba194760fbfc51a808f62543
12:24:51 AM: buildbot version: 1ac64ca11e029436ed45ac81a38b9839778ec314
12:24:51 AM: Fetching cached dependencies
12:24:51 AM: Starting to download cache of 70.1MB
12:24:51 AM: Finished downloading cache in 309.774013ms
12:24:51 AM: Starting to extract cache
12:24:53 AM: Finished extracting cache in 1.389418327s
12:24:53 AM: Finished fetching cache in 1.735306961s
12:24:53 AM: Starting to prepare the repo for build
12:24:53 AM: Preparing Git Reference refs/heads/master
12:24:54 AM: Starting build script
12:24:54 AM: Installing dependencies
12:24:54 AM: Started restoring cached node version
12:24:56 AM: Finished restoring cached node version
12:24:56 AM: v8.15.1 is already installed.
12:24:57 AM: Now using node v8.15.1 (npm v6.4.1)
12:24:57 AM: Attempting ruby version 2.3.6, read from environment
12:24:58 AM: Using ruby version 2.3.6
12:24:59 AM: Using PHP version 5.6
12:24:59 AM: Installing Hugo 0.49.2
12:24:59 AM: Started restoring cached go cache
12:24:59 AM: Finished restoring cached go cache
12:24:59 AM: unset GOOS;
12:24:59 AM: unset GOARCH;
12:24:59 AM: export GOROOT='/opt/buildhome/.gimme/versions/go1.10.linux.amd64';
12:24:59 AM: export PATH="/opt/buildhome/.gimme/versions/go1.10.linux.amd64/bin:${PATH}";
12:24:59 AM: go version >&2;
12:24:59 AM: export GIMME_ENV='/opt/buildhome/.gimme/env/go1.10.linux.amd64.env';
12:24:59 AM: go version go1.10 linux/amd64
12:24:59 AM: Installing missing commands
12:24:59 AM: Verify run directory
12:24:59 AM: Executing user command: hugo
12:24:59 AM: Building sites …
12:24:59 AM: 
12:24:59 AM:                    | EN
12:24:59 AM: +------------------+----+
12:24:59 AM:   Pages            | 10
12:24:59 AM:   Paginator pages  |
12:24:59 AM:  0
12:24:59 AM:   Non-page files   |  0
12:24:59 AM:   Static files     | 90
12:24:59 AM:   Processed images |  0
12:24:59 AM:   Aliases          |  0
12:24:59 AM:   Sitemaps         |
12:24:59 AM:  1
12:24:59 AM:   Cleaned          |  0
12:24:59 AM: Total in 24 ms
12:24:59 AM: Caching artifacts
12:24:59 AM: Started saving pip cache
12:24:59 AM: Finished saving pip cache
12:24:59 AM: Started saving emacs cask dependencies
12:24:59 AM: Finished saving emacs cask dependencies
12:24:59 AM: Started saving maven dependencies
12:24:59 AM: Finished saving maven dependencies
12:24:59 AM: Started saving boot dependencies
12:24:59 AM: Finished saving boot dependencies
12:24:59 AM: Started saving go dependencies
12:24:59 AM: Finished saving go dependencies
12:24:59 AM: Build script success
12:24:59 AM: Starting to deploy site from 'public'
12:24:59 AM: Starting post processing
12:25:00 AM: Post processing done
12:25:00 AM: Site is live
12:25:10 AM: Finished processing build request in 19.357107448s
12:25:10 AM: Shutting down logging, 0 messages pending

Many thanks, @maordano

**Comment by SteveLane** [comment]
Hi @nodoambiental I don't use RStudio, so I can't comment on that, but if it deploys locally and not on netlify, then that surely points to a misconfiguration on netlify's side. Take another look - does it show up in the live preview?

**Comment by nodoambiental** [comment]
Hi @SteveLane. I first reviewed files. Then I try several deploys attempts, all equal with a blank page as outcome. Finally, I search in google about my doubts. The main aid come from @richardlent comment on their webpage:
https://richardlent.github.io/post/how-i-deploy-my-website-to-github-using-rstudio-blogdown-and-hugo/

Specifically, Netlify rightly deploy the web when I add at the header of the config.toml:
canonifyurls = true
relativeURLs = true
publishDir = "../nodoambiental.org"

Then, changes to the live web page are made on the public folder in our github:
https://github.com/nodoambiental/portal-icon

Now, site is live: https://nodoambiental.org

Many thanks @SteveLane @yihui and @richardlent

@maordano @nodoambiental
