### ISSUE TITLE
Configurable url for contacts form

### ISSUE THREAD

**Issue by mr-tron** [SteveLane/hugo-icon#6]
Please add parameter to configuration file for changing `action` in contacts form.
https://github.com/SteveLane/hugo-icon/blob/master/layouts/partials/contact-form.html#L9
For example https://formspree.io/ supports same fields so netlify can be transparent replaced with self-hosted server + formspree

**Comment by SteveLane** [comment]
Hi @mr-tron - are you able to submit a pull request for how you see this working?

**Comment by mr-tron** [comment]
Yes. I am going to do this, but i don`t know when.

**Comment by nodoambiental** [comment]
@mr-tron, The following worked for me.
First, I checked Formspree on the online test with my e-mail.
Then, I modified contact-form as:
<div id="fh5co-contact" data-section="contact">
  <div class="container">
    <div class="col-md-6 col-md-offset-3 text-left fh5co-heading">
      {{ with .Site.Params.contact }}
      <h1>{{ .title }}</h1>
      <p>{{ .message | markdownify }}</p>
      {{ end }}
    </div>
    <form method="POST" action="https://formspree.io/correonodoambiental@gmail.com">
  <input type="email" name="e-mail" placeholder="e-mail">
  <textarea name="message" placeholder="message"></textarea>
  <button type="submit">Send</button>
</form>
     </div>
      </div>

Then, the config.toml as:
# Contact section
[params.contact]
  enable = true
  title = "Contact"
  message = "text."

**Comment by blueyetisoftware** [comment]
@SteveLane and @mr-tron I created a pull request for conversion to formspree. It can either be merged as is or used as inspiration for something that supports both netlify and formspree.

https://github.com/SteveLane/hugo-icon/pull/31

**Comment by SteveLane** [comment]
Thanks @phinatic - I'll leave as is, as I'm happy with netlify, and don't have the time to parameterise the form to accept either. If you implemented a version that used either, I'd be happy to check it out further and perhaps pull it in.
